force-app/main/default/objects/Process__c/Process__c.object-meta.xml
<CustomObject>
    <description
    >Process to be associated to an Opportunity. It contains Process Tasks to be associated to Opportunities.</description>
    <label>Process</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process__c/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <description>Human readable name of the process</description>
    <label>ProcessName</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Processes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProcessTask__c/ProcessTask__c.object-meta.xml
<CustomObject>
    <description>A Task to be performed within a Process</description>
    <label>Process Task</label>
    <nameField>
        <label>Process Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessTask__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Process associated with this ProcessTask</description>
    <label>Process</label>
    <referenceTo>Process__c</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>ProcessTasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProcessTask__c/fields/SequentialOrder__c.field-meta.xml
<CustomField>
    <fullName>SequentialOrder__c</fullName>
    <description>Order that the task stands in the process where it belongs</description>
    <label>Sequential Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Processes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Default Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Special Customer</fullName>
    </customValue>
    <masterLabel>Processes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProcessTaskSelector.cls
/**
 * @description Selector class for the object ProcessTask__c
 *
 * @author  Alvaro Canas
 * @version 0.1
 * @since   21.03.2025
 */
public with sharing class ProcessTaskSelector {
    public static ProcessTask__c[] getProcessTasksByProcessIds(Id[] processIds) {
        return [
            SELECT Id, Process__r.ProcessName__c, SequentialOrder__c
            FROM ProcessTask__c
            WHERE Process__c IN :processIds
            WITH SECURITY_ENFORCED
            ORDER BY SequentialOrder__c ASC
        ];
    }
}