force-app/main/default/objects/Opportunity/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <description>Process used for the Task Sequencer, it will create Opportunity Task Processes to be fulfilled.</description>
    <label>Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Processes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process__c/Process__c.object-meta.xml
<CustomObject>
    <description
    >Process to be associated to an Opportunity. It contains Process Tasks to be associated to Opportunities.</description>
    <label>Process</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process__c/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <description>Human readable name of the process</description>
    <label>ProcessName</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Processes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProcessTask__c/ProcessTask__c.object-meta.xml
<CustomObject>
    <description>A Task to be performed within a Process</description>
    <label>Process Task</label>
    <nameField>
        <label>Process Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessTask__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Process associated with this ProcessTask</description>
    <label>Process</label>
    <referenceTo>Process__c</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>ProcessTasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProcessTask__c/fields/SequentialOrder__c.field-meta.xml
<CustomField>
    <fullName>SequentialOrder__c</fullName>
    <description>Order that the task stands in the process where it belongs</description>
    <label>Sequential Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Processes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Default Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Special Customer</fullName>
    </customValue>
    <masterLabel>Processes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
/**
 * @description Class to create objects for the tests classes
 *
 * @author  Alvaro Canas
 * @version 0.1
 * @since   21.03.2025
 */
@isTest
public with sharing class TestDataFactory {
    public static Process__c createProcess(String name) {
        Process__c proc = new Process__c();
        proc.ProcessName__c = name; // Restricted by Global Picklist
        return proc;
    }

    public static ProcessTask__c createProcessTask(String name, Integer order, Id proId) {
        ProcessTask__c proTas = new ProcessTask__c();
        proTas.Name = name;
        proTas.SequentialOrder__c = order;
        proTas.Process__c = proId;
        return proTas;
    }

    public static Opportunity createOpportunity() {
        Opportunity oppy = new Opportunity();
        oppy.Name = 'Test Opportunity';
        oppy.StageName = 'Prospecting';
        oppy.CloseDate = Date.today().addDays(30);
        return oppy;
    }
}