force-app/main/default/objects/Opportunity/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <description>Process used for the Task Sequencer, it will create Opportunity Task Processes to be fulfilled.</description>
    <label>Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Processes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/OpportunityProcessTask__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Opportunity and ProcessTask</description>
    <label>Opportunity Process Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>OpportunityProcessTask Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Process Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityProcessTask__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description
    >Opportunity that is the Parent in the Master Detail Relationship side of this Junction Object between Opportunity and ProcessTask</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OpportunityProcessTasks</relationshipLabel>
    <relationshipName>OpportunityProcessTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <formula>ProcessTask__r.Process__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Process</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/ProcessTask__c.field-meta.xml
<CustomField>
    <fullName>ProcessTask__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Process Task related to this Junction Object between Opportunity and Process Task</description>
    <label>Process Task</label>
    <referenceTo>ProcessTask__c</referenceTo>
    <relationshipName>OpportunityProcessTasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/SequentialOrder__c.field-meta.xml
<CustomField>
    <fullName>SequentialOrder__c</fullName>
    <formula>ProcessTask__r.SequentialOrder__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sequential Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the task in the sequential process</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process__c/Process__c.object-meta.xml
<CustomObject>
    <description
    >Process to be associated to an Opportunity. It contains Process Tasks to be associated to Opportunities.</description>
    <label>Process</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process__c/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <description>Human readable name of the process</description>
    <label>ProcessName</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Processes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProcessTask__c/ProcessTask__c.object-meta.xml
<CustomObject>
    <description>A Task to be performed within a Process</description>
    <label>Process Task</label>
    <nameField>
        <label>Process Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessTask__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Process associated with this ProcessTask</description>
    <label>Process</label>
    <referenceTo>Process__c</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>ProcessTasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProcessTask__c/fields/SequentialOrder__c.field-meta.xml
<CustomField>
    <fullName>SequentialOrder__c</fullName>
    <description>Order that the task stands in the process where it belongs</description>
    <label>Sequential Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProcessTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Processes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Default Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Special Customer</fullName>
    </customValue>
    <masterLabel>Processes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerHandler.cls
/**
 * @description Handler for the Trigger for Opportunity Object
 *
 * @author  Alvaro Canas
 * @version 0.1
 * @since   21.03.2025
 */
public with sharing class OpportunityTriggerHandler {
    /**
     * @description Method to call the relevant method after trigger is fired
     *
     * @param  triggerOp  Trigger operation
     * @return void
     */
    public static void run(System.TriggerOperation triggerOp) {
        switch on triggerOp {
            when AFTER_INSERT {
                afterInsert(Trigger.newMap);
            }
            when AFTER_UPDATE {
                afterUpdate(Trigger.newMap, Trigger.oldMap);
            }
        }
    }

    /**
     * @description Method called after insert trigger
     *
     * @param  newItems  Trigger variable
     * @return void
     */
    public static void afterInsert(Map<Id, SObject> newItems) {
        Map<Id, Opportunity> newOppies = (Map<Id, Opportunity>) newItems;
        applyProcess(newOppies);
    }

    /**
     * @description Method called after update trigger
     *
     * @param  newItems  Trigger variable
     * @param  oldItems  Trigger variable
     * @return void
     */
    public static void afterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        Map<Id, Opportunity> newOppies = (Map<Id, Opportunity>) newItems;
        applyProcess(newOppies);
    }

    /**
     * @description Apply a new process to a set of Opportunities creating the first step of every Opportunity's process
     *
     * @param  oppies  Map with Opportunities passed by the Variables trigger
     * @return void
     */
    public static void applyProcess(Map<Id, Opportunity> oppies) {
        // First, get all the processes involved
        Set<String> procSet = new Set<String>();
        for (Opportunity opp : oppies.values()) {
            if (opp.Process__c != null) {
                procSet.add(opp.Process__c); // Get processes by name, as they aren't a Lookup
            }
        }

        if (procSet.isEmpty()) {
            return; // Early return if no process present
        }

        // When an Opportunity is created or updated, only the first step of each process is relevant
        ProcessTask__c[] proTasL = [
            SELECT Id, Process__c, Process__r.ProcessName__c
            FROM ProcessTask__c
            WHERE Process__r.ProcessName__c IN :procSet AND SequentialOrder__c = 1
            WITH SECURITY_ENFORCED
        ];

        if (proTasL.isEmpty()) {
            return; // Early return if no ProcessTask__c exist
        }

        // Create Map with ProcessName => ProcessTask__c.Id (Each process with its first step)
        Map<String, Id> processNameToTaskIdMap = createProcessNameToTaskMap(proTasL);

        // Create collection of OpportunityProcessTask__c for later bulk insertion
        OpportunityProcessTask__c[] oppProTaskL = new List<OpportunityProcessTask__c>{};
        for (Opportunity opp : oppies.values()) {
            if (opp.Process__c == null) {
                continue; // Early return if an Opportunity doesn't have a Process
            }
            // Create junction objects
            OpportunityProcessTask__c opPrTask = new OpportunityProcessTask__c();
            opPrTask.Opportunity__c = opp.Id;
            opPrTask.ProcessTask__c = processNameToTaskIdMap.get(opp.Process__c);
            opPrTask.Status__c = 'Not Started';
            oppProTaskL.add(opPrTask);
        }

        // Bulk insertion of the new steps
        insert oppProTaskL;
    }

    /**
     * @description Creates a Map of Processes with assoviated with the Id of the first task related to that process
     *
     * @param  proTasL  Collection of Process Tasks
     * @return void
     */
    public static Map<String, Id> createProcessNameToTaskMap(ProcessTask__c[] proTasL) {
        Map<String, Id> processNameToTaskIdMap = new Map<String, Id>();
        for (ProcessTask__c proTak : proTasL) {
            if (!processNameToTaskIdMap.containsKey(proTak.Process__r.ProcessName__c)) {
                processNameToTaskIdMap.put(proTak.Process__r.ProcessName__c, proTak.Id);
            } else {
                // This means the process name is duplicated or there are more than one process task with order 1
                // For the first case, it is a opportunity for improvement that would be solved if Process is a lookup reference instead a picklist
                // Then, the match would be done by unique Id instead of possible dublicated name
                // For the second case, there should be a validation for not having more than one step in the same process with same order number
            }
        }
        return processNameToTaskIdMap;
    }
}