force-app/main/default/objects/Opportunity/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <description>Process used for the Task Sequencer, it will create Opportunity Task Processes to be fulfilled.</description>
    <label>Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Processes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/OpportunityProcessTask__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Opportunity and ProcessTask</description>
    <label>Opportunity Process Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>OpportunityProcessTask Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Process Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityProcessTask__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description
    >Opportunity that is the Parent in the Master Detail Relationship side of this Junction Object between Opportunity and ProcessTask</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OpportunityProcessTasks</relationshipLabel>
    <relationshipName>OpportunityProcessTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <formula>ProcessTask__r.Process__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Process</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/ProcessTask__c.field-meta.xml
<CustomField>
    <fullName>ProcessTask__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Process Task related to this Junction Object between Opportunity and Process Task</description>
    <label>Process Task</label>
    <referenceTo>ProcessTask__c</referenceTo>
    <relationshipName>OpportunityProcessTasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/SequentialOrder__c.field-meta.xml
<CustomField>
    <fullName>SequentialOrder__c</fullName>
    <formula>ProcessTask__r.SequentialOrder__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sequential Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the task in the sequential process</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process__c/Process__c.object-meta.xml
<CustomObject>
    <description
    >Process to be associated to an Opportunity. It contains Process Tasks to be associated to Opportunities.</description>
    <label>Process</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessTask__c/ProcessTask__c.object-meta.xml
<CustomObject>
    <description>A Task to be performed within a Process</description>
    <label>Process Task</label>
    <nameField>
        <label>Process Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessTask__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Process associated with this ProcessTask</description>
    <label>Process</label>
    <referenceTo>Process__c</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>ProcessTasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProcessTask__c/fields/SequentialOrder__c.field-meta.xml
<CustomField>
    <fullName>SequentialOrder__c</fullName>
    <description>Order that the task stands in the process where it belongs</description>
    <label>Sequential Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProcessTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Processes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Default Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Special Customer</fullName>
    </customValue>
    <masterLabel>Processes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityProcessTaskTriggerHandlerTest.cls
/**
 * @description Test for the Handler Trigger in OpportunityProcessTask__c Object
 *
 * @author  Alvaro Canas
 * @version 0.1
 * @since   21.03.2025
 */
@isTest
public with sharing class OpportunityProcessTaskTriggerHandlerTest {
    public static final String PROCESS_NAME = 'Default Customer'; // Restricted by Global Picklist
    public static final String PROCESS_NAME2 = 'Special Customer'; // Restricted by Global Picklist

    @TestSetup
    static void makeData() {
        Process__c proc = TestDataFactory.createProcess(PROCESS_NAME);
        insert proc;

        ProcessTask__c proTas1 = TestDataFactory.createProcessTask('Step1 - Process 1', 1, proc.Id);
        ProcessTask__c proTas2 = TestDataFactory.createProcessTask('Step2 - Process 1', 2, proc.Id);
        insert new List<ProcessTask__c>{ proTas1, proTas2 };

        Opportunity oppy = TestDataFactory.createOpportunity();
        oppy.Process__c = PROCESS_NAME;
        insert oppy;

        OpportunityProcessTask__c[] opt = [SELECT Id FROM OpportunityProcessTask__c];
        System.assertEquals(1, opt.size(), 'Expected one OpportunityProcessTask__c created');
    }

    @isTest
    public static void stepCompletedTest() {
        // Given a OpportunityProcessTask__c
        OpportunityProcessTask__c[] opt = [SELECT Id, Opportunity__c FROM OpportunityProcessTask__c];

        // When the Status changes to Completed
        opt[0].Status__c = 'Completed';
        Test.startTest();
        update opt;
        Test.stopTest();

        // Then, a new step has been created in the relevant opportunity
        OpportunityProcessTask__c[] tasks = [
            SELECT Id, SequentialOrder__c
            FROM OpportunityProcessTask__c
            WHERE Opportunity__c = :opt[0].Opportunity__c
            ORDER BY SequentialOrder__c ASC
        ];
        System.assertEquals(2, tasks.size(), 'Expected two OpportunityProcessTask__c created');

        for (Integer i = 0; i < tasks.size(); i++) {
            System.assertEquals(
                i,
                Integer.valueOf(tasks[i].SequentialOrder__c) - 1,
                'Expected two OpportunityProcessTask__c created in expected order'
            );
        }
    }

    @isTest
    public static void multipleCompletedStepsTest() {
        // Get Opportunity 1
        Opportunity oppy1 = [SELECT Id FROM Opportunity];

        // Given multiple OpportunityProcessTask__c in different stages
        Process__c proc2 = TestDataFactory.createProcess(PROCESS_NAME2);
        insert proc2;

        ProcessTask__c proTas1 = TestDataFactory.createProcessTask('Step1 - Second Process', 1, proc2.Id);
        ProcessTask__c proTas2 = TestDataFactory.createProcessTask('Step2 - Second Process', 2, proc2.Id);
        ProcessTask__c proTas3 = TestDataFactory.createProcessTask('Step3 - Second Process', 3, proc2.Id);
        insert new List<ProcessTask__c>{ proTas1, proTas2, proTas3 };

        Opportunity oppy2 = TestDataFactory.createOpportunity();
        oppy2.Process__c = PROCESS_NAME2;
        insert oppy2;

        // Move second process one step ahead
        OpportunityProcessTask__c opt = getLastStepFromOppy(oppy2.Id);
        opt.Status__c = 'Completed';
        update opt;

        // When multiple OpportunityProcessTask__c are completed
        OpportunityProcessTask__c opt1 = getLastStepFromOppy(oppy1.Id);
        OpportunityProcessTask__c opt2 = getLastStepFromOppy(oppy2.Id);

        opt1.Status__c = 'Completed';
        opt2.Status__c = 'Completed';

        Test.startTest();
        update new List<OpportunityProcessTask__c>{ opt1, opt2 };
        Test.stopTest();

        // Then, each next OpportunityProcessTask__c has been created
        // First Oppy has OpportunityProcessTask__c in step 2
        OpportunityProcessTask__c stepInOppy1 = getLastStepFromOppy(oppy1.Id);
        System.assertEquals(2, stepInOppy1.SequentialOrder__c, 'Expected first Opportunity to be in Second Step');
        // Second Oppy has OpportunityProcessTask__c in step 3
        OpportunityProcessTask__c stepInOppy2 = getLastStepFromOppy(oppy2.Id);
        System.assertEquals(3, stepInOppy2.SequentialOrder__c, 'Expected first Opportunity to be in Third Step');
    }

    @isTest
    public static void lastStepCompletedTest() {
        // Given a Last step in a process
        OpportunityProcessTask__c opt = [SELECT Id, Opportunity__c FROM OpportunityProcessTask__c];
        opt.Status__c = 'Completed';
        update opt;

        // When the last step is completed
        OpportunityProcessTask__c lastOpt = getLastStepFromOppy(opt.Opportunity__c);
        lastOpt.Status__c = 'Completed';
        Test.startTest();
        update opt;
        Test.stopTest();

        // Then, no new task is created
        OpportunityProcessTask__c[] tasks = [SELECT Id FROM OpportunityProcessTask__c WHERE Opportunity__c = :opt.Opportunity__c];
        System.assertEquals(2, tasks.size(), 'Expected two OpportunityProcessTask__c created');
    }

    @isTest
    public static void irrelevantUpdateTest() {
        // Given a OpportunityProcessTask__c
        OpportunityProcessTask__c[] opt = [SELECT Id, Opportunity__c FROM OpportunityProcessTask__c];

        // When updating it but not as Completed
        opt[0].Status__c = 'Failed';
        Test.startTest();
        update opt;
        Test.stopTest();

        // Then, there is still only one OpportunityProcessTask__c
        opt = [SELECT Id, Opportunity__c FROM OpportunityProcessTask__c];
        System.assertEquals(1, opt.size(), 'Expected one OpportunityProcessTask__c');
    }

    @isTest
    public static void beforeDeleteTest() {
        // Given a OpportunityProcessTask__c
        OpportunityProcessTask__c[] opt = [SELECT Id, Opportunity__c FROM OpportunityProcessTask__c];
        System.assertEquals(1, opt.size(), 'Expected one OpportunityProcessTask__c');

        // When deleting the OpportunityProcessTask__c
        Test.startTest();
        delete opt;
        Test.stopTest();

        // Then, no OpportunityProcessTask__c should remain
        opt = [SELECT Id, Opportunity__c FROM OpportunityProcessTask__c];
        System.assertEquals(0, opt.size(), 'Expected no OpportunityProcessTask__c');
    }

    /**
     * @description Returns a the last step of a given opportunity Id
     *
     * @param  procIds List of Project Ids
     * @return Map<String, List<ProcessTask__c>>
     */
    public static OpportunityProcessTask__c getLastStepFromOppy(Id oppyId) {
        return [
            SELECT Id, SequentialOrder__c
            FROM OpportunityProcessTask__c
            WHERE Opportunity__c = :oppyId
            ORDER BY SequentialOrder__c DESC
            LIMIT 1
        ];
    }
}