force-app/main/default/objects/Opportunity/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <description>Process used for the Task Sequencer, it will create Opportunity Task Processes to be fulfilled.</description>
    <label>Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Processes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/OpportunityProcessTask__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Opportunity and ProcessTask</description>
    <label>Opportunity Process Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>OpportunityProcessTask Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Process Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityProcessTask__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description
    >Opportunity that is the Parent in the Master Detail Relationship side of this Junction Object between Opportunity and ProcessTask</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OpportunityProcessTasks</relationshipLabel>
    <relationshipName>OpportunityProcessTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <formula>ProcessTask__r.Process__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Process</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/ProcessTask__c.field-meta.xml
<CustomField>
    <fullName>ProcessTask__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Process Task related to this Junction Object between Opportunity and Process Task</description>
    <label>Process Task</label>
    <referenceTo>ProcessTask__c</referenceTo>
    <relationshipName>OpportunityProcessTasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the task in the sequential process</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/StepName__c.field-meta.xml
<CustomField>
    <fullName>StepName__c</fullName>
    <formula>ProcessTask__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Step Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process__c/Process__c.object-meta.xml
<CustomObject>
    <description
    >Process to be associated to an Opportunity. It contains Process Tasks to be associated to Opportunities.</description>
    <label>Process</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessTask__c/ProcessTask__c.object-meta.xml
<CustomObject>
    <description>A Task to be performed within a Process</description>
    <label>Process Task</label>
    <nameField>
        <label>Process Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessTask__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Process associated with this ProcessTask</description>
    <label>Process</label>
    <referenceTo>Process__c</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>ProcessTasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProcessTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Processes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Default Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Special Customer</fullName>
    </customValue>
    <masterLabel>Processes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerHandlerTest.cls
/**
 * @description Test for the Handler Trigger in Opportunity Object
 *
 * @author  Alvaro Canas
 * @version 0.1
 * @since   21.03.2025
 */
@isTest
public with sharing class OpportunityTriggerHandlerTest {
    public static final String PROCESS_NAME = 'Default Customer'; // Restricted by Global Picklist
    public static final String PROCESS_NAME2 = 'Special Customer'; // Restricted by Global Picklist

    @TestSetup
    static void makeData() {
        Process__c proc = TestDataFactory.createProcess(PROCESS_NAME);
        insert proc;

        ProcessTask__c proTas1 = TestDataFactory.createProcessTask('Step1', 1, proc.Id);
        ProcessTask__c proTas2 = TestDataFactory.createProcessTask('Step2', 2, proc.Id);
        insert new List<ProcessTask__c>{ proTas1, proTas2 };

        Opportunity oppy = TestDataFactory.createOpportunity();
        insert oppy;
    }

    @isTest
    public static void afterInsertTest() {
        // Given an Opportunity with a Process
        Opportunity oppy = TestDataFactory.createOpportunity();
        oppy.Process__c = PROCESS_NAME;

        // When the Opportunity is inserted
        Test.startTest();
        insert oppy;
        Test.stopTest();

        // Then, the opportunity has one OpportunityProcessTask__c and it's the first step of the process
        OpportunityProcessTask__c[] oppProcTask = [
            SELECT Id, StepName__c, Status__c
            FROM OpportunityProcessTask__c
            WHERE Opportunity__c = :oppy.Id
        ];
        System.assertEquals(1, oppProcTask.size(), 'Expected one OpportunityProcessTask__c');
        System.assertEquals('Step1', oppProcTask[0].StepName__c, 'Expected the OpportunityProcessTask__c to be the first step');
    }

    @isTest
    public static void afterInsertBulkTest() {
        // Given multiple Processes, Steps and Opportunities
        Process__c proc2 = TestDataFactory.createProcess(PROCESS_NAME2);
        insert proc2;

        ProcessTask__c proTas1 = TestDataFactory.createProcessTask('Step1 - Process 2', 1, proc2.Id);
        ProcessTask__c proTas2 = TestDataFactory.createProcessTask('Step2 - Process 2', 2, proc2.Id);
        insert new List<ProcessTask__c>{ proTas1, proTas2 };

        Opportunity oppy = TestDataFactory.createOpportunity();
        oppy.Process__c = PROCESS_NAME;

        Opportunity oppy2 = TestDataFactory.createOpportunity();
        oppy2.Process__c = PROCESS_NAME2;

        Opportunity[] oppL = new List<Opportunity>{ oppy, oppy2 };

        // When the Opportunity is inserted
        Test.startTest();
        insert oppL;
        Test.stopTest();

        // Then, each Opportunity has their OpportunityProcessTask__c and it's the first step of the process
        OpportunityProcessTask__c[] oppProcTask = [
            SELECT Id, StepName__c, Status__c
            FROM OpportunityProcessTask__c
            WHERE Opportunity__c = :oppL[0].Id
        ];
        System.assertEquals(1, oppProcTask.size(), 'Expected one OpportunityProcessTask__c');
        System.assertEquals('Step1', oppProcTask[0].StepName__c, 'Expected the OpportunityProcessTask__c to be the first step');

        OpportunityProcessTask__c[] oppProcTask2 = [
            SELECT Id, StepName__c, Status__c
            FROM OpportunityProcessTask__c
            WHERE Opportunity__c = :oppL[1].Id
        ];
        System.assertEquals(1, oppProcTask2.size(), 'Expected one OpportunityProcessTask__c');
        System.assertEquals(
            'Step1 - Process 2',
            oppProcTask2[0].StepName__c,
            'Expected the OpportunityProcessTask__c to be the first step'
        );
    }

    @isTest
    public static void afterUpdateTest() {
        // Given an Opportunity
        Opportunity oppy = [SELECT Id FROM Opportunity LIMIT 1];

        // When the Status of the opportunity is updated
        oppy.Process__c = PROCESS_NAME;
        Test.startTest();
        update oppy;
        Test.stopTest();

        // Then, the opportunity has one OpportunityProcessTask__c and it's the first step of the process
        OpportunityProcessTask__c[] oppProcTask = [
            SELECT Id, StepName__c, Status__c
            FROM OpportunityProcessTask__c
            WHERE Opportunity__c = :oppy.Id
        ];
        System.assertEquals(1, oppProcTask.size(), 'Expected one OpportunityProcessTask__c');
        System.assertEquals('Step1', oppProcTask[0].StepName__c, 'Expected the OpportunityProcessTask__c to be the first step');
    }

    @isTest
    public static void afterUpdateBulkTest() {
        // Given multiple processes and steps
        Process__c proc2 = TestDataFactory.createProcess(PROCESS_NAME2);
        insert proc2;

        ProcessTask__c proTas1 = TestDataFactory.createProcessTask('Step1 - Process 2', 1, proc2.Id);
        ProcessTask__c proTas2 = TestDataFactory.createProcessTask('Step2 - Process 2', 2, proc2.Id);
        insert new List<ProcessTask__c>{ proTas1, proTas2 };

        Opportunity oppy = TestDataFactory.createOpportunity();
        insert oppy;

        Opportunity[] oppyL = [SELECT Id FROM Opportunity];
        System.assertEquals(2, oppyL.size(), 'Expected two Opportunities');

        // When the Status of the opportunities are updated
        oppyL[0].Process__c = PROCESS_NAME;
        oppyL[1].Process__c = PROCESS_NAME2;
        Test.startTest();
        update oppyL;
        Test.stopTest();

        // Then, each Opportunity has their OpportunityProcessTask__c and it's the first step of the process
        OpportunityProcessTask__c[] oppProcTask = [
            SELECT Id, StepName__c, Status__c
            FROM OpportunityProcessTask__c
            WHERE Opportunity__c = :oppyL[0].Id
        ];
        System.assertEquals(1, oppProcTask.size(), 'Expected one OpportunityProcessTask__c');
        System.assertEquals('Step1', oppProcTask[0].StepName__c, 'Expected the OpportunityProcessTask__c to be the first step');

        OpportunityProcessTask__c[] oppProcTask2 = [
            SELECT Id, StepName__c, Status__c
            FROM OpportunityProcessTask__c
            WHERE Opportunity__c = :oppyL[1].Id
        ];
        System.assertEquals(1, oppProcTask2.size(), 'Expected one OpportunityProcessTask__c');
        System.assertEquals(
            'Step1 - Process 2',
            oppProcTask2[0].StepName__c,
            'Expected the OpportunityProcessTask__c to be the first step'
        );
    }
}