force-app/main/default/objects/OpportunityProcessTask__c/OpportunityProcessTask__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Opportunity and ProcessTask</description>
    <label>Opportunity Process Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>OpportunityProcessTask Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Process Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityProcessTask__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description
    >Opportunity that is the Parent in the Master Detail Relationship side of this Junction Object between Opportunity and ProcessTask</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OpportunityProcessTasks</relationshipLabel>
    <relationshipName>OpportunityProcessTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityProcessTask__c/fields/SequentialOrder__c.field-meta.xml
<CustomField>
    <fullName>SequentialOrder__c</fullName>
    <formula>ProcessTask__r.SequentialOrder__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sequential Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityProcessTaskSelector.cls
/**
 * @description Selector class for the object OpportunityProcessTask__c
 *
 * @author  Alvaro Canas
 * @version 0.1
 * @since   21.03.2025
 */
public with sharing class OpportunityProcessTaskSelector {
    public static OpportunityProcessTask__c[] getTasksByOpportunityIds(Id[] ids) {
        return [
            SELECT Id, SequentialOrder__c, Opportunity__c
            FROM OpportunityProcessTask__c
            WHERE Opportunity__c IN :ids
            WITH SECURITY_ENFORCED
            ORDER BY SequentialOrder__c ASC
        ];
    }
}